import { ref } from "vue";

const totalData = ref([
  {
    id: "#01",
    name: "Barbara Freeman",
    startDate: "03 Dec, 2023",
    endDate: "03 Feb, 2024",
    planType: "Professional",
    totalPayment: "$39.99",
    status: "Successfully",
  },
  {
    id: "#02",
    name: "Paula Dennis",
    startDate: "25 Jan, 2024",
    endDate: "25 April, 2024",
    planType: "Enterprise",
    totalPayment: "$59.99",
    status: "Failed",
  },
  {
    id: "#03",
    name: "Martin Wexler",
    startDate: "10 Jan, 2024",
    endDate: "10 Jan, 2025",
    planType: "Enterprise",
    totalPayment: "$499.99",
    status: "Successfully",
  },
  {
    id: "#04",
    name: "Jasmine Moore",
    startDate: "16 Feb, 2024",
    endDate: "16 Jun, 2024",
    planType: "Basic",
    totalPayment: "$29.99",
    status: "Pending",
  },
  {
    id: "#05",
    name: "Josh Davison",
    startDate: "18 Feb, 2024",
    endDate: "18 Jan, 2025",
    planType: "Professional",
    totalPayment: "$59.99",
    status: "Successfully",
  },
  {
    id: "#06",
    name: "Grace Gibbons",
    startDate: "03 April, 2024",
    endDate: "03 Sep, 2025",
    planType: "Professional",
    totalPayment: "$49.99",
    status: "Successfully",
  },
  {
    id: "#07",
    name: "Anthony Dennis",
    startDate: "16 Jan, 2024",
    endDate: "16 Jan, 2025",
    planType: "Professional",
    totalPayment: "$499.99",
    status: "Pending",
  },
  {
    id: "#08",
    name: "Olivia Stephens",
    startDate: "03 Dec, 2023",
    endDate: "03 Fab, 2023",
    planType: "Professional",
    totalPayment: "$39.99",
    status: "Successfully",
  },
  {
    id: "#09",
    name: "David Brown",
    startDate: "03 Jan, 2024",
    endDate: "03 Jan, 2024",
    planType: "Enterprise",
    totalPayment: "$39.99",
    status: "Failed",
  },
  {
    id: "#10",
    name: "Jennifer Bolton",
    startDate: "03 Jan, 2024",
    endDate: "03 Jan, 2024",
    planType: "Professional",
    totalPayment: "$39.99",
    status: "Successfully",
  },
]);

export { totalData };
