import {
  AlignStartVertical,
  BarChart3,
  BookOpen,
  Box,
  Calendar,
  Clipboard,
  Dna,
  Feather,
  FileText,
  FileTextIcon,
  Folders,
  Gauge,
  Gem,
  Hospital,
  KeyRound,
  LifeBuoy,
  Mail,
  Map,
  MessagesSquare,
  Monitor,
  PencilRuler,
  RemoveFormatting,
  ScatterChart,
  School,
  Shapes,
  ShoppingBag,
  Table2,
  TextQuote,
  TrendingUpDownIcon,
  Trophy,
  UsersRound,
} from "lucide-vue-next";

var menu: any = [
  {
    separator: true,
    title: "Dashboards",
    lang: "pe-dashboards",
    children: [],
  },
  {
    title: "Dashboards",
    lang: "pe-dashboards",
    icon: Gauge,
    link: "",
    separator: false,
    children: [
      {
        title: "eCommerce",
        lang: "pe-ecommerce",
        link: "e-commerce",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Analytics",
        lang: "pe-analytics",
        link: "dashboards-analytics",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Email",
        lang: "pe-email",
        link: "dashboard-email",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "CRM",
        lang: "pe-crm",
        link: "dashboards-crm",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Hospital",
        lang: "pe-hospital",
        link: "dashboards-hospital",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "File Manager",
        lang: "pe-file-manager",
        link: "dashboards-file-manager",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Project",
        lang: "pe-project",
        link: "dashboards-projects",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "School",
        lang: "pe-school",
        link: "dashboards-school",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Music",
        lang: "pe-music",
        link: "dashboard-music",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Landing Page",
    lang: "pe-landing-page",
    icon: Box,
    link: "",
    separator: false,
    children: [
      {
        title: "eCommerce",
        lang: "pe-ecommerce",
        link: "landing-ecommerce",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Email",
        lang: "pe-email",
        link: "landing-email",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Invoice",
        lang: "pe-invoice",
        link: "landing-invoice",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "School",
        lang: "pe-school",
        link: "landing-school",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Doctors",
        lang: "pe-doctors",
        link: "landing-doctors",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    separator: true,
    title: "Apps",
    lang: "pe-apps",
    children: [],
  },
  {
    title: "Chat",
    lang: "pe-chat",
    icon: MessagesSquare,
    link: "",
    separator: false,
    children: [
      {
        title: "Default",
        lang: "pe-default",
        link: "apps-chat-default",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Group",
        lang: "pe-group",
        link: "apps-chat-group",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Video Call",
        lang: "pe-video-call",
        link: "apps-chat-group-video",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Calendar",
    lang: "pe-calendar",
    icon: Calendar,
    link: "",
    separator: false,
    children: [
      {
        title: "Default",
        lang: "pe-default",
        link: "apps-calendar-default",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Week Number",
        lang: "pe-week-number",
        link: "apps-calendar-weeknumber",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Localize",
        lang: "pe-localize",
        link: "apps-calendar-localize",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Day View",
        lang: "pe-day-view",
        link: "apps-calendar-dayview",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "List View",
        lang: "pe-list-view",
        link: "apps-calendar-listview",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Time Grid View",
        lang: "pe-time-grid-view",
        link: "apps-calendar-timegrid",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Multi-Month Stack",
        lang: "pe-multi-month-stack",
        link: "apps-calendar-multi-month-stack",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Multi-Month Grid",
        lang: "pe-multi-month-grid",
        link: "apps-calendar-multi-month-grid",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Timeline",
        lang: "pe-timeline",
        link: "apps-calendar-timeline",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Date Nav Link",
        lang: "pe-date-nav-link",
        link: "apps-calendar-date-nav-link",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Clicking & Selecting",
        lang: "pe-clicking-selecting",
        link: "apps-calendar-date-clicking",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Email",
    lang: "pe-email",
    icon: Mail,
    link: "",
    separator: false,
    children: [
      {
        title: "Mailbox",
        lang: "pe-mailbox",
        link: "apps-mailbox",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Templates",
        link: "",
        lang: "pe-templates",
        children: [
          {
            title: "Welcome",
            lang: "pe-welcome",
            link: "apps-email-templates-welcome",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Newsletter",
            lang: "pe-newsletter",
            link: "apps-email-templates-newsletter",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: "Ecommerce",
    lang: "pe-ecommerce",
    icon: ShoppingBag,
    link: "",
    separator: false,
    children: [
      {
        title: "Products",
        link: "",
        lang: "pe-products",
        children: [
          {
            title: "List View",
            lang: "pe-list-view",
            link: "apps-ecommerce-products-list",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Grid View",
            lang: "pe-grid-view",
            link: "apps-ecommerce-products-grid",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Add New",
            lang: "pe-add-new",
            link: "apps-ecommerce-create-products",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Overview",
            lang: "pe-overview",
            link: "apps-ecommerce-product-overview",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Category List",
            lang: "pe-category-list",
            link: "apps-ecommerce-category",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Orders",
        link: "",
        lang: "pe-orders",
        children: [
          {
            title: "List View",
            lang: "pe-list-view",
            link: "apps-ecommerce-orders-list",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Overview",
            lang: "pe-overview",
            link: "apps-ecommerce-orders-overview",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Track",
            lang: "pe-track",
            link: "apps-ecommerce-orders-track",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Customers",
        link: "",
        lang: "pe-customers",
        children: [
          {
            title: "List View",
            lang: "pe-list-view",
            link: "apps-ecommerce-customer-list",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Overview",
            lang: "pe-overview",
            link: "apps-ecommerce-customer-user",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Shop Cart",
        lang: "pe-shop-cart",
        link: "apps-ecommerce-shop-cart",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Checkout",
        lang: "pe-checkout",
        link: "apps-ecommerce-checkout",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Wishlist",
        lang: "pe-wishlist",
        link: "apps-ecommerce-wishlist",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Payment",
        lang: "pe-payment",
        link: "apps-ecommerce-payment",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Manage Reviews",
        lang: "pe-manage-reviews",
        link: "apps-ecommerce-manage-reviews",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "File Manager",
    lang: "pe-file-manager",
    icon: Folders,
    link: "apps-file-manager",
    separator: false,
    dropdownPosition: null,
    children: [],
  },
  {
    title: "Projects",
    lang: "pe-projects",
    icon: Monitor,
    link: "",
    separator: false,
    children: [
      {
        title: "List View",
        lang: "pe-list-view",
        link: "apps-projects-list",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Grid View",
        lang: "pe-grid-view",
        link: "apps-projects-grid",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Overview",
        lang: "pe-overview",
        link: "apps-projects-overview",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "RoadMap",
        lang: "pe-roadmap",
        link: "apps-projects-roadmap",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Task",
        lang: "pe-task",
        link: "apps-projects-task",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Files",
        lang: "pe-files",
        link: "apps-projects-files",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Users",
        lang: "pe-users",
        link: "apps-projects-users",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "CRM",
    lang: "pe-crm",
    icon: Shapes,
    link: "",
    separator: false,
    children: [
      {
        title: "Lead",
        lang: "pe-lead",
        link: "apps-crm-lead",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Contact",
        lang: "pe-contact",
        link: "apps-crm-contact",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Deal",
        lang: "pe-deal",
        link: "apps-crm-deal",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Events",
    lang: "pe-events",
    icon: Trophy,
    link: "",
    separator: false,
    children: [
      {
        title: "Events List",
        lang: "pe-events-list",
        link: "apps-events-list",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Events Grid",
        lang: "pe-events-grid",
        link: "apps-events-grid",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Overview",
        lang: "pe-overview",
        link: "apps-event-overview",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Hospital Management",
    lang: "pe-hospital-management",
    icon: Hospital,
    link: "",
    separator: false,
    children: [
      {
        title: "Patients",
        link: "",
        lang: "pe-patients",
        children: [
          {
            title: "List View",
            lang: "pe-list-view",
            link: "apps-hospital-patients-lists",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Add Patient",
            lang: "pe-add-patients",
            link: "apps-hospital-patients-create",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Patient Profile",
            lang: "pe-patients-profile",
            link: "apps-hospital-patients-overview",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Staff",
        link: "",
        lang: "pe-staff",
        children: [
          {
            title: "List View",
            lang: "pe-list-view",
            link: "apps-hospital-staff-lists",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Leaves",
            lang: "pe-leaves",
            link: "apps-hospital-staff-leaves",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Add Leave",
            lang: "pe-add-leave",
            link: "apps-hospital-staff-leave-add",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Holidays",
            lang: "pe-holidays",
            link: "apps-hospital-staff-holidays",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Attendance",
            lang: "pe-attendance",
            link: "apps-hospital-staff-attendance",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Appointments",
        link: "",
        lang: "pe-appointments",
        children: [
          {
            title: "List View",
            lang: "pe-list-view",
            link: "apps-hospital-appointments-lists",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Book Appointment",
            lang: "pe-book-appointment",
            link: "apps-hospital-appointments-book",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Doctor Schedule",
        lang: "pe-doctor-schedule",
        link: "apps-hospital-doctor-schedule",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Departments",
        lang: "pe-departments",
        link: "apps-hospital-departments",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Payroll",
        link: "",
        lang: "pe-payroll",
        children: [
          {
            title: "Employee Salary",
            lang: "pe-employee-salary",
            link: "apps-hospital-payroll-employee-salary",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Payslip",
            lang: "pe-payslip",
            link: "apps-hospital-payroll-payslip",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: "School",
    lang: "pe-school",
    icon: School,
    link: "",
    separator: false,
    children: [
      {
        title: "Students",
        link: "",
        lang: "pe-students",
        children: [
          {
            title: "All Students",
            lang: "pe-all-students",
            link: "apps-school-students-list",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Overview",
            lang: "pe-overview",
            link: "apps-school-students-overview",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Admission Form",
            lang: "pe-admission-form",
            link: "apps-school-students-admission",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Teachers",
        link: "",
        lang: "pe-teachers",
        children: [
          {
            title: "All Teachers",
            lang: "pe-all-teachers",
            link: "apps-school-teachers-list",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Overview",
            lang: "pe-overview",
            link: "apps-school-teachers-overview",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Payroll",
            lang: "pe-payroll",
            link: "apps-school-teachers-payroll",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Parents",
        lang: "pe-parents",
        link: "apps-school-parents",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Library Book",
        lang: "pe-library-book",
        link: "apps-school-library-book",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Attendances",
        lang: "pe-attendances",
        link: "apps-school-attendances-students",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Exam",
        link: "",
        lang: "pe-exam",
        children: [
          {
            title: "Schedule",
            lang: "pe-schedule",
            link: "apps-school-exam-schedule",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Exam Question",
            lang: "pe-exam-question",
            link: "apps-school-exam-question",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: "Invoice",
    lang: "pe-invoice",
    icon: FileText,
    link: "",
    separator: false,
    children: [
      {
        title: "List View",
        lang: "pe-list-view",
        link: "apps-invoice-list",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Grid View",
        lang: "pe-grid-view",
        link: "apps-invoice-grid",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Add New",
        lang: "pe-add-new",
        link: "apps-invoice-create",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Overview 1",
        lang: "pe-overview-1",
        link: "apps-invoice-overview-1",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Overview 2",
        lang: "pe-overview-2",
        link: "apps-invoice-overview-2",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    separator: true,
    title: "Pages",
    lang: "pe-pages",
    children: [],
  },
  {
    title: "Authentication",
    lang: "pe-authentication",
    icon: UsersRound,
    link: "",
    separator: false,
    children: [
      {
        title: "Sign In",
        link: "",
        lang: "pe-sign-in",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-signin-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-signin-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-signin-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Sign Up",
        link: "",
        lang: "pe-sign-up",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-signup-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-signup-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-signup-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Forgot Password",
        link: "",
        lang: "pe-forgot-password",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-forgot-password-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-forgot-password-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-forgot-password-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Two Step Verification",
        link: "",
        lang: "pe-two-step-verification",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-two-step-verification-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-two-step-verification-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-two-step-verification-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Reset Password",
        link: "",
        lang: "pe-reset-password",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-reset-password-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-reset-password-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-reset-password-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Successful Password",
        link: "",
        lang: "pe-successful-password",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-successful-password-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-successful-password-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-successful-password-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Account Deactivation",
        link: "",
        lang: "pe-account-deactivation",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "auth-account-deactivation-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Modern",
            lang: "pe-modern",
            link: "auth-account-deactivation-modern",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Creative",
            lang: "pe-creative",
            link: "auth-account-deactivation-creative",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: "Pages",
    lang: "pe-pages",
    icon: Box,
    link: "",
    separator: false,
    children: [
      {
        title: "Blank",
        lang: "pe-blank",
        link: "pages-starter",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Account",
        link: "",
        lang: "pe-account",
        children: [
          {
            title: "Account",
            lang: "pe-account",
            link: "pages-account-settings",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Security",
            lang: "pe-security",
            link: "pages-account-security",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Billing & Plans",
            lang: "pe-billing-plans",
            link: "pages-account-billing-plan",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Notification",
            lang: "pe-notification",
            link: "pages-account-notification",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Statements",
            lang: "pe-statements",
            link: "pages-account-statements",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Logs",
            lang: "pe-logs",
            link: "pages-account-logs",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "User Profile",
        link: "",
        lang: "pe-user-profile",
        children: [
          {
            title: "Overview",
            lang: "pe-overview",
            link: "pages-user",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Activity",
            lang: "pe-activity",
            link: "pages-user-activity",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Followers",
            lang: "pe-followers",
            link: "pages-user-followers",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Documents",
            lang: "pe-documents",
            link: "pages-user-documents",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Notes",
            lang: "pe-notes",
            link: "pages-user-notes",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Projects",
            lang: "pe-projects",
            link: "pages-user-projects",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Pricing",
        link: "",
        lang: "pe-pricing",
        children: [
          {
            title: "User",
            lang: "pe-user",
            link: "pages-pricing",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Admin",
            lang: "pe-admin",
            link: "pages-pricing-admin",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
      {
        title: "Contact Us",
        lang: "pe-contact-us",
        link: "pages-contact-us",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "FAQ's",
        lang: "pe-faqs",
        link: "pages-faq",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Licenses",
        lang: "pe-licenses",
        link: "pages-licenses",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Coming Soon",
        lang: "pe-coming-soon",
        link: "pages-coming-soon",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Maintenance",
        lang: "pe-maintenance",
        link: "pages-maintenance",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Privacy Policy",
        lang: "pe-privacy-policy",
        link: "pages-privacy-policy",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Help Center",
        lang: "pe-help-center",
        link: "pages-help-center",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Error Pages",
        link: "",
        lang: "pe-error-pages",
        children: [
          {
            title: "404",
            lang: "pe-404",
            link: "pages-404",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "500",
            lang: "pe-500",
            link: "pages-500",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: "Widgets",
    lang: "pe-widgets",
    icon: AlignStartVertical,
    link: "",
    separator: false,
    children: [
      {
        title: "Cards",
        lang: "pe-cards",
        link: "widgets-cards",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Banners",
        lang: "pe-banners",
        link: "widgets-banners",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Charts",
        lang: "pe-charts",
        link: "widgets-charts",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Data",
        lang: "pe-data",
        link: "widgets-data",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    separator: true,
    title: "Components",
    lang: "pe-components",
    children: [],
  },
  {
    title: "UI Elements",
    lang: "pe-ui-elements",
    icon: KeyRound,
    link: "",
    separator: false,
    megaMenu: true,
    children: [
      {
        title: "Alerts",
        lang: "pe-alerts",
        link: "ui-alerts",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Badges",
        lang: "pe-badges",
        link: "ui-badge",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Breadcrumb",
        lang: "pe-breadcrumb",
        link: "ui-breadcrumb",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Buttons Group",
        lang: "pe-buttons-group",
        link: "ui-buttons-group",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Buttons",
        lang: "pe-buttons",
        link: "ui-buttons",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Buttons Navigation",
        lang: "pe-buttons-navigation",
        link: "ui-button-navigation",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Dropdown",
        lang: "pe-dropdown",
        link: "ui-dropdown",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Loader",
        lang: "pe-loader",
        link: "ui-loader",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Accordion",
        lang: "pe-accordion",
        link: "ui-accordion",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Modal",
        lang: "pe-modal",
        link: "ui-modal",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Links",
        lang: "pe-links",
        link: "ui-links",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Tabs",
        lang: "pe-tabs",
        link: "ui-tabs",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Drawer",
        lang: "pe-drawer",
        link: "ui-drawer",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Pagination",
        lang: "pe-pagination",
        link: "ui-pagination",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Progress Bar",
        lang: "pe-progress-bar",
        link: "ui-progress-bar",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Tooltips",
        lang: "pe-tooltips",
        link: "ui-tooltips",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Cards",
        lang: "pe-cards",
        link: "ui-cards",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Timeline",
        lang: "pe-timeline",
        link: "ui-timeline",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Notification",
        lang: "pe-notification",
        link: "ui-notification",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "List Group",
        lang: "pe-list-group",
        link: "ui-list-group",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Cookie Consent",
        lang: "pe-cookie-consent",
        link: "ui-cookie",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Gallery",
        lang: "pe-gallery",
        link: "ui-gallery",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Video",
        lang: "pe-video",
        link: "ui-video",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Colors",
        lang: "pe-colors",
        link: "ui-colors",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Typography",
        lang: "pe-typography",
        link: "ui-typography",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Advanced UI",
    lang: "pe-advanced-ui",
    icon: Gem,
    link: "",
    separator: false,
    children: [
      {
        title: "Animation",
        lang: "pe-animation",
        link: "ui-advanced-animation",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Simplebar",
        lang: "pe-simplebar",
        link: "ui-advanced-simplebar",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Swiper",
        lang: "pe-swiper",
        link: "ui-advanced-swiper",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "3D Effect",
        lang: "pe-3d-effect",
        link: "ui-advanced-3d-effect",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Word Counter",
        lang: "pe-word-counter",
        link: "ui-advanced-word-counter",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Chat Bot",
        lang: "pe-chat-bot",
        link: "ui-advanced-bot",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Images Annotation",
        lang: "pe-images-annotation",
        link: "ui-advanced-image-annotation",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Tree Map",
        lang: "pe-tree-map",
        link: "ui-advanced-tree",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Highlight Code",
        lang: "pe-highlight-code",
        link: "ui-advanced-highlight",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Mask Input",
        lang: "pe-mask-input",
        link: "ui-advanced-mask",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Icons",
    lang: "pe-icons",
    icon: PencilRuler,
    link: "",
    separator: false,
    children: [
      {
        title: "Lucide",
        lang: "pe-lucide",
        link: "icons-lucide",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Remix Icons",
        lang: "pe-remix-icons",
        link: "icons-remix",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Heroicons",
        lang: "pe-heroicons",
        link: "icons-heroicons",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Boxicon",
        lang: "pe-boxicon",
        link: "icons-boxicon",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Line Awesome",
        lang: "pe-line-awesome",
        link: "icons-line-awesome",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    separator: true,
    title: "Forms & Tables",
    lang: "pe-forms-tables",
    children: [],
  },
  {
    title: "Forms",
    lang: "pe-forms",
    icon: BookOpen,
    link: "",
    separator: false,
    children: [
      {
        title: "Basic Input",
        lang: "pe-basic-input",
        link: "form-basic-input",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Input Group",
        lang: "pe-input-group",
        link: "form-input-group",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "File Upload",
        lang: "pe-file-upload",
        link: "form-file-input",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Pickers",
        lang: "pe-pickers",
        link: "form-pickers",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Sliders",
        lang: "pe-sliders",
        link: "form-range",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Switches",
        lang: "pe-switches",
        link: "form-switches",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Checkbox & Radio",
        lang: "pe-checkbox-radio",
        link: "form-checkbox-radio",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Input Spin",
        lang: "pe-input-spin",
        link: "form-input-spin",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "reCAPTCHA",
        lang: "pe-recaptcha",
        link: "form-recaptcha",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Autosize",
        lang: "pe-autosize",
        link: "form-autosize",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Editors",
    lang: "pe-editors",
    icon: RemoveFormatting,
    link: "form-editors",
    separator: false,
    dropdownPosition: null,
    children: [],
  },
  {
    title: "Clipboard",
    lang: "pe-clipboard",
    icon: Clipboard,
    link: "form-clipboard",
    separator: false,
    dropdownPosition: null,
    children: [],
  },
  {
    title: "Form Wizard",
    lang: "pe-form-wizard",
    icon: TextQuote,
    link: "form-wizard-basic",
    separator: false,
    dropdownPosition: null,
    children: [],
  },
  {
    title: "Tables",
    lang: "pe-tables",
    icon: Table2,
    separator: false,
    link: "",
    children: [
      {
        title: "Base",
        lang: "pe-base",
        link: "table-base",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Data Tables",
        link: "",
        lang: "pe-data-tables",
        children: [
          {
            title: "Basic",
            lang: "pe-basic",
            link: "table-datatables-basic",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Bordered",
            lang: "pe-bordered",
            link: "table-datatables-bordered",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Stripe",
            lang: "pe-stripe",
            link: "table-datatables-stripe",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Hover Effect",
            lang: "pe-hover-effect",
            link: "table-datatables-hover",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Row Grouping",
            lang: "pe-row-grouping",
            link: "table-datatables-row-grouping",
            dropdownPosition: null,
            children: [],
          },
          {
            title: "Feature enable / disable",
            lang: "pe-feature-enable-disable",
            link: "table-datatables-enable-disable",
            dropdownPosition: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    separator: true,
    title: "Charts & Maps",
    lang: "pe-charts-maps",
    children: [],
  },
  {
    title: "Apexcharts",
    lang: "pe-apexcharts",
    icon: BarChart3,
    separator: false,
    link: "",
    children: [
      {
        title: "Area",
        lang: "pe-area",
        link: "apexchart-area",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Bar",
        lang: "pe-bar",
        link: "apexchart-bar",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Box Whisher",
        lang: "pe-box-whisher",
        link: "apexchart-box-whisker",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Bubble",
        lang: "pe-bubble",
        link: "apexchart-bubble",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Candlestick",
        lang: "pe-candlestick",
        link: "apexchart-candlestick",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Column",
        lang: "pe-column",
        link: "apexchart-column",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Funnel",
        lang: "pe-funnel",
        link: "apexchart-funnel",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Heatmap",
        lang: "pe-heatmap",
        link: "apexchart-heatmap",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Line",
        lang: "pe-line",
        link: "apexchart-line",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Mixed",
        lang: "pe-mixed",
        link: "apexchart-mixed",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Pie",
        lang: "pe-pie",
        link: "apexchart-pie",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Polar Area",
        lang: "pe-polar-area",
        link: "apexchart-polar-area",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Radar",
        lang: "pe-radar",
        link: "apexchart-radar",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Radialbar",
        lang: "pe-radialbar",
        link: "apexchart-radialbar",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Range Area",
        lang: "pe-range-area",
        link: "apexchart-range-area",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Scatter",
        lang: "pe-scatter",
        link: "apexchart-scatter",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Slope",
        lang: "pe-slope",
        link: "apexchart-slope",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Timeline",
        lang: "pe-timeline",
        link: "apexchart-timeline",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Treemap",
        lang: "pe-treemap",
        link: "apexchart-treemap",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Apextree",
    lang: "pe-apextree",
    icon: TrendingUpDownIcon,
    separator: false,
    link: "",
    children: [
      {
        title: "Top to Bottom",
        lang: "pe-top-to-bottom",
        link: "apextree-top-bottom",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Bottom to Top",
        lang: "pe-bottom-to-top",
        link: "apextree-bottom-top",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Left to Right",
        lang: "pe-left-to-right",
        link: "apextree-left-right",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Right to Left",
        lang: "pe-right-to-left",
        link: "apextree-right-left",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Collapse Expand",
        lang: "pe-collapse-expand",
        link: "apextree-collapse-expand",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "ApexSankey",
    lang: "pe-apexsankey",
    icon: Dna,
    separator: false,
    link: "charts-apexsankey",
    dropdownPosition: null,
    children: [],
  },
  {
    title: "Echarts",
    lang: "pe-echarts",
    icon: ScatterChart,
    separator: false,
    link: "",
    children: [
      {
        title: "Bar",
        lang: "pe-bar",
        link: "echart-bar",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Line",
        lang: "pe-line",
        link: "echart-line",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Pie",
        lang: "pe-pie",
        link: "echart-pie",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    title: "Maps",
    lang: "pe-maps",
    icon: Map,
    separator: false,
    link: "",
    children: [
      {
        title: "Google Maps",
        lang: "pe-google-maps",
        link: "maps-google",
        dropdownPosition: null,
        children: [],
      },
      {
        title: "Vector",
        lang: "pe-vector",
        link: "maps-vector",
        dropdownPosition: null,
        children: [],
      },
    ],
  },
  {
    separator: true,
    title: "Docs & ChangeLog",
    lang: "pe-docs-changeLog",
    children: [],
  },
  {
    title: "Support",
    lang: "pe-support",
    icon: LifeBuoy,
    separator: false,
    link: "https://1.envato.market/domiex-admin-dashboard-support",
    dropdownPosition: null,
    children: [],
  },
  {
    title: "Documentation",
    lang: "pe-documentation",
    icon: FileTextIcon,
    separator: false,
    link: "https://srbthemes.kcubeinfotech.com/domiex/docs/vue/index.html",
    dropdownPosition: null,
    children: [],
  },
  {
    title: "ChangeLog",
    lang: "pe-changelog",
    icon: Feather,
    separator: false,
    link: "https://srbthemes.kcubeinfotech.com/domiex/live/changelog.html",
    dropdownPosition: null,
    children: [],
  },
];

export default menu;
